### ISSUE TITLE
Bad file descriptor when running pgctl-in-pgctl under python3

### ISSUE THREAD

**Issue by asottile** [Yelp/pgctl#139]
Naively you end up with output that looks like this if you try and make sub-playgrounds within a pgctl service:

```
$ pgctl debug scrapers
[pgctl] Stopping: scrapers
[pgctl] Stopped: scrapers
[pgctl] Stopping: scraper_pscrp1, scraper_pscrp2, scraper_pscrp3
[pgctl] Stopped: scraper_pscrp1
[pgctl] Stopped: scraper_pscrp2
[pgctl] Stopped: scraper_pscrp3
Traceback (most recent call last):
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/bin/pgctl", line 11, in <module>
    sys.exit(main())
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/cli.py", line 436, in main
    return app()
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/cli.py", line 142, in __call__
    result = command()
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/cli.py", line 265, in stop
    failed = self.__change_state(stop)
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/cli.py", line 183, in __change_state
    return self.__locked_change_state(state)
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/contextlib2.py", line 414, in __exit__
    _reraise_with_existing_context(exc_details)
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/contextlib2.py", line 276, in _reraise_with_existing_context
    raise exc_details[1]
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/contextlib2.py", line 403, in __exit__
    if cb(*exc_details):
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/contextlib2.py", line 331, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/flock.py", line 84, in flock
    os.close(fd)
OSError: [Errno 9] Bad file descriptor
[pgctl] Stopping: scraper_pscrp1, scraper_pscrp2, scraper_pscrp3
[pgctl] Stopped: scraper_pscrp1
[pgctl] Stopped: scraper_pscrp2
[pgctl] Stopped: scraper_pscrp3
Traceback (most recent call last):
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/bin/pgctl", line 11, in <module>
    sys.exit(main())
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/cli.py", line 436, in main
    return app()
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/cli.py", line 142, in __call__
    result = command()
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/cli.py", line 265, in stop
    failed = self.__change_state(stop)
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/cli.py", line 183, in __change_state
    return self.__locked_change_state(state)
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/contextlib2.py", line 414, in __exit__
    _reraise_with_existing_context(exc_details)
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/contextlib2.py", line 276, in _reraise_with_existing_context
    raise exc_details[1]
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/contextlib2.py", line 403, in __exit__
    if cb(*exc_details):
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/contextlib2.py", line 331, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/asottile/workspace/PokemonGo-Map-dev/venv/lib/python3.5/site-packages/pgctl/flock.py", line 84, in flock
    os.close(fd)
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/home/asottile/workspace/PokemonGo-Map-dev/playground/scrapers/run", line 58, in main
    remove_old_scrapers()
  File "/home/asottile/workspace/PokemonGo-Map-dev/playground/scrapers/run", line 29, in remove_old_scrapers
    subprocess.check_call(('pgctl', 'stop'))
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('pgctl', 'stop')' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asottile/workspace/PokemonGo-Map-dev/playground/scrapers/run", line 68, in <module>
    exit(main())
  File "/home/asottile/workspace/PokemonGo-Map-dev/playground/scrapers/run", line 64, in main
    remove_old_scrapers()
  File "/home/asottile/workspace/PokemonGo-Map-dev/playground/scrapers/run", line 29, in remove_old_scrapers
    subprocess.check_call(('pgctl', 'stop'))
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('pgctl', 'stop')' returned non-zero exit status 1
```

Here's a workaround:

``` python
def no_pgctl_environ():
    # We're using pgctl-in-pgctl, clear all pgctl related variables
    for k in tuple(os.environ):
        if k.startswith('PGCTL_'):
            del os.environ[k]
```

**Comment by bukzor** [comment]
It's not 100% clear how to reproduce this, but I believe that once we figure out what's going wrong, we can make this use case work as expected, without this env clear workaround.

**Comment by asottile** [comment]
Ya know, I'm having a difficult time making a minimal reproduction.  Commenting out this line seems to trigger it for me with `pgctl debug scrapers`:

https://github.com/asottile/PokemonGo-Map/pull/38/commits/c611639a6b4074d8e9032d142813d6e80e9c6571#diff-fe032982004fe4532a3d59fb71773d2bR65

**Comment by asottile** [comment]
Here's a minimal reproduction:

```
$ cat playground/s1/run 
#!/usr/bin/env python
import subprocess
subprocess.check_call(('pgctl', 'stop'))
$ cat playground/s1/playground/inner/run 
#!/usr/bin/env bash
exec sleep infinity
```

```
$ pgctl debug s1
[pgctl] Stopping: s1
[pgctl] Stopped: s1
[pgctl] Stopping: inner
[pgctl] Stopped: inner
Traceback (most recent call last):
  File "/tmp/foo/venv/bin/pgctl", line 11, in <module>
    sys.exit(main())
  File "/tmp/foo/venv/lib/python3.5/site-packages/pgctl/cli.py", line 436, in main
    return app()
  File "/tmp/foo/venv/lib/python3.5/site-packages/pgctl/cli.py", line 142, in __call__
    result = command()
  File "/tmp/foo/venv/lib/python3.5/site-packages/pgctl/cli.py", line 265, in stop
    failed = self.__change_state(stop)
  File "/tmp/foo/venv/lib/python3.5/site-packages/pgctl/cli.py", line 183, in __change_state
    return self.__locked_change_state(state)
  File "/tmp/foo/venv/lib/python3.5/site-packages/contextlib2.py", line 414, in __exit__
    _reraise_with_existing_context(exc_details)
  File "/tmp/foo/venv/lib/python3.5/site-packages/contextlib2.py", line 276, in _reraise_with_existing_context
    raise exc_details[1]
  File "/tmp/foo/venv/lib/python3.5/site-packages/contextlib2.py", line 403, in __exit__
    if cb(*exc_details):
  File "/tmp/foo/venv/lib/python3.5/site-packages/contextlib2.py", line 331, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/tmp/foo/venv/lib/python3.5/site-packages/pgctl/flock.py", line 84, in flock
    os.close(fd)
OSError: [Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/tmp/foo/playground/s1/run", line 3, in <module>
    subprocess.check_call(('pgctl', 'stop'))
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('pgctl', 'stop')' returned non-zero exit status 1
```

**Comment by asottile** [comment]
Oh you know what, this seems to only affect python3.5, changing this to bug :D
