### ISSUE TITLE
cd'ing from home directory results in pgctl not knowing where the playground dir is

### ISSUE THREAD

**Issue by kentwills** [Yelp/pgctl#40]
```
(virtualenv_run)(www_pages/master) rkwills@dev24-devc:~/trees/yelp/www_pages 
[Mon 08-17 05:03:17PM]$ cd assets
(virtualenv_run)(www_pages/master) rkwills@dev24-devc:~/trees/yelp/www_pages/assets 
[Wed 08-19 09:19:43AM]$ pgctl-2015 start
Starting: 
Traceback (most recent call last):
  File "/nail/home/rkwills/trees/yelp/www_pages/virtualenv_run/bin/pgctl-2015", line 9, in <module>
    load_entry_point('pgctl==0.0.2', 'console_scripts', 'pgctl-2015')()
  File "/nail/home/rkwills/trees/yelp/pgctl/pgctl/cli.py", line 259, in main
    return app()
  File "/nail/home/rkwills/trees/yelp/pgctl/pgctl/cli.py", line 74, in __call__
    return command()
  File "/nail/home/rkwills/trees/yelp/pgctl/pgctl/cli.py", line 97, in start
    return self.__change_state('-u', 'up', 'Starting:', 'Started:')
  File "/nail/home/rkwills/trees/yelp/pgctl/pgctl/cli.py", line 79, in __change_state
    with self.pgdir.as_cwd():
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/nail/home/rkwills/trees/yelp/www_pages/virtualenv_run/lib/python2.7/site-packages/py/_path/local.py", line 562, in as_cwd
    old = self.chdir()
  File "/nail/home/rkwills/trees/yelp/www_pages/virtualenv_run/lib/python2.7/site-packages/py/_path/local.py", line 553, in chdir
    py.error.checked_call(os.chdir, self.strpath)
  File "/nail/home/rkwills/trees/yelp/www_pages/virtualenv_run/lib/python2.7/site-packages/py/_error.py", line 84, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.ENOENT: [No such file or directory]: chdir(u'/nail/home/rkwills/trees/yelp/www_pages/assets/playground',)
```

**Comment by bukzor** [comment]
fixed by #50
